apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: locust-master
  labels:
    app.kubernetes.io/part-of: locust
spec:
  selector:
    matchLabels:
      app: locust-master
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s