apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.41.5
        imagePullPolicy: IfNotPresent
        args: ["-f","/mnt/locust/locustfile.py","--master","--web-host","0.0.0.0"]
        env:
        - name: LOCUST_HOST
          value: "http://backend:8080/nexus"
        ports:
        - name: web
          containerPort: 8089
        - name: comm
          containerPort: 5557
        - name: comm2
          containerPort: 5558
        resources:
          requests: { cpu: "100m", memory: "256Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
        volumeMounts:
        - name: locustfile
          mountPath: /mnt/locust
      - name: exporter
        image: containersol/locust_exporter:latest
        env:
        - name: LOCUST_EXPORTER_URI
          value: "http://localhost:8089"
        ports:
        - name: metrics
          containerPort: 9646
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "128Mi" }
      volumes:
      - name: locustfile
        configMap:
          name: locustfile