apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    app: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.41.5
        args: ["-f","/mnt/locust/locustfile.py","--worker","--master-host","locust-master"]
        env:
        - name: LOCUST_HOST
          value: "http://backend:8080/nexus"  # patched per overlay
        resources:
          requests: { cpu: "200m", memory: "512Mi" }
          limits:   { cpu: "1000m", memory: "1Gi" }
        volumeMounts:
        - name: locustfile
          mountPath: /mnt/locust
      volumes:
      - name: locustfile
        configMap:
          name: locustfile