apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  type: ClusterIP
  selector:
    app: locust-master
  ports:
  - name: web
    port: 8089
    targetPort: web