kind: pipeline
type: kubernetes
name: dev
timeout: 120
trigger: { branch: [dev], event: [push] }
service_account_name: drone-pipeline

steps:
  - name: build-backend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=info
      - --context=dir://$DRONE_WORKSPACE/backend
      - --dockerfile=$DRONE_WORKSPACE/backend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/backend-image.txt   # <-- record digest
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 10Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 20Gi }

  - name: frontend-build
    image: node:20-bullseye
    environment:
      npm_config_fund: "false"
      npm_config_audit: "false"
      npm_config_progress: "false"
      npm_config_fetch_retries: "8"
      npm_config_fetch_retry_mintimeout: "30000"
      npm_config_fetch_retry_maxtimeout: "180000"
      npm_config_network_timeout: "600000"
      NODE_OPTIONS: "--max-old-space-size=1536"
    commands:
      - cd frontend
      - npm ci --no-audit --no-fund --loglevel=warn
      - npm run build
      - npm prune --omit=dev --omit=optional
      - npm dedupe --omit=dev || true
      - ls -lh build || true
      - du -sh build node_modules || true
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 16Gi }

  - name: build-frontend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=debug
      - --context=dir://$DRONE_WORKSPACE/frontend
      - --dockerfile=$DRONE_WORKSPACE/frontend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/frontend-image.txt  # <-- record digest
    resources:
      requests: { cpu: 1000, memory: 1Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 2Gi, ephemeral_storage: 16Gi }

  - name: deploy
    image: alpine/k8s:1.30.3
    pull: if-not-exists
    working_dir: /drone/src
    resources:
      requests: { cpu: 500, memory: 512Mi, ephemeral_storage: 2Gi }
      limits:   { cpu: 2000, memory: 1Gi,   ephemeral_storage: 4Gi }
    environment:
      PROJECT_ID: spectra-kube
      REGION: us-central1
      REPO: nexus
      APP_SECRETS_ENV:
        from_secret: dev_secrets_env
    commands:
      - |
        set -eux

        # 1) required env + registry (still deploys fine even if these are blank because we use digests)
        : "${PROJECT_ID:?missing}"; : "${REGION:?missing}"; : "${REPO:?missing}"
        REGISTRY="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}"
        printf '[deploy] registry=%s\n' "$REGISTRY"

        # 2) ensure overlay secret file exists for kustomize
        mkdir -p k8s/overlays/dev
        if [ -n "${APP_SECRETS_ENV:-}" ]; then
          printf '%s\n' "$APP_SECRETS_ENV" > k8s/overlays/dev/secrets.env
        else
          : > k8s/overlays/dev/secrets.env
        fi

        # 3) apply infra (svc/cm/ing/policies/etc)
        kubectl apply -k k8s/overlays/dev

        # 4) image digests (strip CR/LF), fallback to tag if files missing
        bfile=/drone/src/backend-image.txt
        ffile=/drone/src/frontend-image.txt
        BACKEND_IMG=""; FRONTEND_IMG=""
        [ -s "$bfile" ] && BACKEND_IMG="$(tr -d '\r\n' < "$bfile")" || BACKEND_IMG="${REGISTRY}/nexus-backend:${DRONE_COMMIT_SHA}"
        [ -s "$ffile" ] && FRONTEND_IMG="$(tr -d '\r\n' < "$ffile")" || FRONTEND_IMG="${REGISTRY}/nexus-frontend:${DRONE_COMMIT_SHA}"

        printf '[deploy] backend -> %s\n' "$BACKEND_IMG"
        printf '[deploy] frontend -> %s\n' "$FRONTEND_IMG"

        # 5) rollout behavior hardening on both deployments
        #    - Always pull (avoid cached image), quicker failures, zero unavailability
        kubectl -n dev patch deploy/backend  --type='merge' -p '{
          "spec":{
            "progressDeadlineSeconds":600,
            "strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":0,"maxSurge":1}},
            "template":{"spec":{
              "terminationGracePeriodSeconds":15,
              "containers":[{"name":"backend","imagePullPolicy":"Always"}]
            }}
          }
        }' || true

        kubectl -n dev patch deploy/frontend --type='merge' -p '{
          "spec":{
            "progressDeadlineSeconds":600,
            "strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":0,"maxSurge":1}},
            "template":{"spec":{
              "terminationGracePeriodSeconds":15,
              "containers":[{"name":"frontend","imagePullPolicy":"Always"}]
            }}
          }
        }' || true

        # 6) set images by digest/tag
        kubectl -n dev set image deploy/backend  backend="$BACKEND_IMG"
        kubectl -n dev set image deploy/frontend frontend="$FRONTEND_IMG"

        echo "[deploy] images now set to:"
        kubectl -n dev get deploy backend  -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'
        kubectl -n dev get deploy frontend -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'

        # 7) wait for rollout with extended timeout; on failure, dump useful diagnostics
        set +e
        kubectl -n dev rollout status deploy/backend  --timeout=600s
        BK_RC=$?
        kubectl -n dev rollout status deploy/frontend --timeout=600s
        FE_RC=$?
        set -e

        if [ $BK_RC -ne 0 ] || [ $FE_RC -ne 0 ]; then
          echo "== DIAGNOSTICS =="
          echo "-- ReplicaSets --"
          kubectl -n dev get rs -o wide
          echo "-- Pods --"
          kubectl -n dev get pods -o wide
          echo "-- Events (last 100) --"
          kubectl -n dev get events --sort-by=.metadata.creationTimestamp | tail -n 100 || true

          echo "-- Describe backend --"
          kubectl -n dev describe deploy/backend || true
          kubectl -n dev describe rs -l app=backend || true
          kubectl -n dev describe pods -l app=backend || true

          echo "-- Describe frontend --"
          kubectl -n dev describe deploy/frontend || true
          kubectl -n dev describe rs -l app=frontend || true
          kubectl -n dev describe pods -l app=frontend || true

          echo "-- Recent logs (backend) --"
          BK_POD="$(kubectl -n dev get pods -l app=backend -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)"
          [ -n "$BK_POD" ] && kubectl -n dev logs "$BK_POD" --all-containers --tail=200 || true

          echo "-- Recent logs (frontend) --"
          FE_POD="$(kubectl -n dev get pods -l app=frontend -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)"
          [ -n "$FE_POD" ] && kubectl -n dev logs "$FE_POD" --all-containers --tail=200 || true

          exit 1
        fi

---
kind: pipeline
type: kubernetes
name: uat
trigger: { branch: [uat], event: [push] }
service_account_name: drone-pipeline

steps:
  - name: build-backend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    
    args:
      - --verbosity=info
      - --context=dir://$DRONE_WORKSPACE/backend
      - --dockerfile=$DRONE_WORKSPACE/backend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshotMode=time
      - --use-new-run
    volumes:
      - name: docker-config
        path: /kaniko/.docker

  - name: frontend-build
    image: node:20-bullseye
    environment:
      npm_config_fund: "false"
      npm_config_audit: "false"
      npm_config_progress: "false"
      npm_config_fetch_retries: "8"
      npm_config_fetch_retry_mintimeout: "30000"
      npm_config_fetch_retry_maxtimeout: "180000"
      npm_config_network_timeout: "600000"
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - tar -czf build.tgz build
      - npm prune --omit=dev
      - tar -czf node_modules.tgz node_modules
      - du -sh build node_modules || true

  - name: build-frontend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    resources:
      requests: { cpu: 1, memory: 1Gi }
      limits:   { cpu: 2, memory: 4Gi }
    
    args:
      - --verbosity=debug
      - --context=dir://$DRONE_WORKSPACE/frontend
      - --dockerfile=$DRONE_WORKSPACE/frontend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshotMode=time
      - --use-new-run
    volumes:
      - name: docker-config
        path: /kaniko/.docker

  - name: deploy
    image: bitnami/kubectl:1.30
    environment: { PROJECT_ID: spectra-kube, REGION: us-central1, REPO: nexus }
    commands:
      - mkdir -p kustom-override/uat
      - |
        cat > kustom-override/uat/kustomization.yaml <<EOF
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
          - ../../k8s/overlays/uat
        images:
          - name: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-backend
            newName: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-backend
            newTag: ${DRONE_COMMIT_SHA}
          - name: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-frontend
            newName: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-frontend
            newTag: ${DRONE_COMMIT_SHA}
        EOF
      - kubectl apply -k kustom-override/uat
      - kubectl -n uat rollout status deploy/backend --timeout=300s
      - kubectl -n uat rollout status deploy/frontend --timeout=300s

---
kind: pipeline
type: kubernetes
name: main
trigger: { branch: [main], event: [push] }
service_account_name: drone-pipeline

steps:
  - name: build-backend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    
    args:
      - --verbosity=info
      - --context=dir://$DRONE_WORKSPACE/backend
      - --dockerfile=$DRONE_WORKSPACE/backend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshotMode=time
      - --use-new-run
    volumes:
      - name: docker-config
        path: /kaniko/.docker

  - name: frontend-build
    image: node:20-bullseye
    environment:
      npm_config_fund: "false"
      npm_config_audit: "false"
      npm_config_progress: "false"
      npm_config_fetch_retries: "8"
      npm_config_fetch_retry_mintimeout: "30000"
      npm_config_fetch_retry_maxtimeout: "180000"
      npm_config_network_timeout: "600000"
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - tar -czf build.tgz build
      - npm prune --omit=dev
      - tar -czf node_modules.tgz node_modules
      - du -sh build node_modules || true

  - name: build-frontend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    resources:
      requests: { cpu: 1, memory: 1Gi }
      limits:   { cpu: 2, memory: 4Gi }
    
    args:
      - --verbosity=debug
      - --context=dir://$DRONE_WORKSPACE/frontend
      - --dockerfile=$DRONE_WORKSPACE/frontend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshotMode=time
      - --use-new-run
    volumes:
      - name: docker-config
        path: /kaniko/.docker

  - name: deploy
    image: bitnami/kubectl:1.30
    environment: { PROJECT_ID: spectra-kube, REGION: us-central1, REPO: nexus }
    commands:
      - mkdir -p kustom-override/main
      - |
        cat > kustom-override/main/kustomization.yaml <<EOF
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
          - ../../k8s/overlays/main
        images:
          - name: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-backend
            newName: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-backend
            newTag: ${DRONE_COMMIT_SHA}
          - name: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-frontend
            newName: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/nexus-frontend
            newTag: ${DRONE_COMMIT_SHA}
        EOF
      - kubectl apply -k kustom-override/main
      - kubectl -n main rollout status deploy/backend --timeout=300s
      - kubectl -n main rollout status deploy/frontend --timeout=300s