kind: pipeline
type: kubernetes
name: dev
timeout: 120
trigger: { branch: [dev], event: [push] }
service_account_name: drone-pipeline

steps:
  - name: build-backend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=info
      - --context=dir://$DRONE_WORKSPACE/backend
      - --dockerfile=$DRONE_WORKSPACE/backend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/backend-image.txt   # <-- record digest
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 10Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 20Gi }

  - name: frontend-build
    image: node:20-bullseye
    environment:
      npm_config_fund: "false"
      npm_config_audit: "false"
      npm_config_progress: "false"
      npm_config_fetch_retries: "8"
      npm_config_fetch_retry_mintimeout: "30000"
      npm_config_fetch_retry_maxtimeout: "180000"
      npm_config_network_timeout: "600000"
      NODE_OPTIONS: "--max-old-space-size=1536"
    commands:
      - cd frontend
      - npm ci --no-audit --no-fund --loglevel=warn
      - npm run build
      - npm prune --omit=dev --omit=optional
      - npm dedupe --omit=dev || true
      - ls -lh build || true
      - du -sh build node_modules || true
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 16Gi }

  - name: build-frontend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=debug
      - --context=dir://$DRONE_WORKSPACE/frontend
      - --dockerfile=$DRONE_WORKSPACE/frontend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/frontend-image.txt  # <-- record digest
    resources:
      requests: { cpu: 1000, memory: 1Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 2Gi, ephemeral_storage: 16Gi }

  - name: deploy
    image: alpine/k8s:1.30.3
    pull: if-not-exists
    working_dir: /drone/src
    resources:
      requests: { cpu: 500, memory: 512Mi, ephemeral_storage: 2Gi }
      limits:   { cpu: 2000, memory: 1Gi,   ephemeral_storage: 4Gi }
    environment:
      PROJECT_ID: spectra-kube
      REGION: us-central1
      REPO: nexus
      APP_SECRETS_ENV:
        from_secret: dev_secrets_env
    commands:
      - |
        set -eux

        # 1) required env + registry (we still prefer digests, but this is used as fallback)
        : "${PROJECT_ID:?missing}"; : "${REGION:?missing}"; : "${REPO:?missing}"
        REGISTRY="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}"
        printf '[deploy] registry=%s\n' "$REGISTRY"

        # 2) ensure overlay secret file exists with real contents
        mkdir -p k8s/overlays/dev

        # Prefer repo file for dev (branch-specific), else use Drone secret
        if [ -f backend/.env.dev ]; then
          # normalize line endings
          tr -d '\r' < backend/.env.dev > k8s/overlays/dev/secrets.env
        elif [ -n "${APP_SECRETS_ENV:-}" ]; then
          printf '%s\n' "$APP_SECRETS_ENV" | tr -d '\r' > k8s/overlays/dev/secrets.env
        else
          echo "ERROR: no secrets provided (backend/.env.dev missing and APP_SECRETS_ENV empty)"; exit 1
        fi

        # Validate required keys (add more if your deployment expects more)
        for k in DB_USER DB_PASS; do
          grep -E "^[[:space:]]*$k=" k8s/overlays/dev/secrets.env >/dev/null || {
            echo "ERROR: required key '$k' missing in secrets.env"; exit 1; }
        done

        # 3) apply infra (svc/cm/ing/secrets from secretGenerator)
        kubectl apply -k k8s/overlays/dev

        # 4) image digests (strip CR/LF), fallback to tags if files not present
        bfile=/drone/src/backend-image.txt
        ffile=/drone/src/frontend-image.txt
        BACKEND_IMG=""; FRONTEND_IMG=""

        [ -s "$bfile" ] && BACKEND_IMG="$(tr -d '\r\n' < "$bfile")" || BACKEND_IMG="${REGISTRY}/nexus-backend:${DRONE_COMMIT_SHA}"
        [ -s "$ffile" ] && FRONTEND_IMG="$(tr -d '\r\n' < "$ffile")" || FRONTEND_IMG="${REGISTRY}/nexus-frontend:${DRONE_COMMIT_SHA}"

        printf '[deploy] backend -> %s\n' "$BACKEND_IMG"
        printf '[deploy] frontend -> %s\n' "$FRONTEND_IMG"

        # 5) set exact images and wait
        kubectl -n dev set image deploy/backend  backend="$BACKEND_IMG"
        kubectl -n dev set image deploy/frontend frontend="$FRONTEND_IMG"

        # show what’s set
        kubectl -n dev get deploy backend  -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'
        kubectl -n dev get deploy frontend -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'

        # 6) wait; if backend fails, print useful diagnostics
        set +e
        kubectl -n dev rollout status deploy/frontend --timeout=600s
        FE_RC=$?
        kubectl -n dev rollout status deploy/backend  --timeout=600s
        BK_RC=$?
        set -e

        if [ $BK_RC -ne 0 ] || [ $FE_RC -ne 0 ]; then
          echo "== DIAGNOSTICS =="
          kubectl -n dev get rs -o wide
          kubectl -n dev get pods -o wide
          kubectl -n dev get events --sort-by=.metadata.creationTimestamp | tail -n 100 || true
          kubectl -n dev describe deploy/backend || true
          kubectl -n dev describe pods -l app=backend || true
          exit 1
        fi

---
kind: pipeline
type: kubernetes
name: uat
trigger: { branch: [uat], event: [push] }
service_account_name: drone-pipeline

steps:
  - name: build-backend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=info
      - --context=dir://$DRONE_WORKSPACE/backend
      - --dockerfile=$DRONE_WORKSPACE/backend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/backend-image.txt
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 10Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 20Gi }

  - name: frontend-build
    image: node:20-bullseye
    environment:
      npm_config_fund: "false"
      npm_config_audit: "false"
      npm_config_progress: "false"
      npm_config_fetch_retries: "8"
      npm_config_fetch_retry_mintimeout: "30000"
      npm_config_fetch_retry_maxtimeout: "180000"
      npm_config_network_timeout: "600000"
      NODE_OPTIONS: "--max-old-space-size=1536"
    commands:
      - cd frontend
      - npm ci --no-audit --no-fund --loglevel=warn
      - npm run build
      - npm prune --omit=dev --omit=optional
      - npm dedupe --omit=dev || true
      - ls -lh build || true
      - du -sh build node_modules || true
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 16Gi }

  - name: build-frontend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=debug
      - --context=dir://$DRONE_WORKSPACE/frontend
      - --dockerfile=$DRONE_WORKSPACE/frontend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/frontend-image.txt
    resources:
      requests: { cpu: 1000, memory: 1Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 2Gi, ephemeral_storage: 16Gi }

  - name: deploy
    image: alpine/k8s:1.30.3
    pull: if-not-exists
    working_dir: /drone/src
    resources:
      requests: { cpu: 500, memory: 512Mi, ephemeral_storage: 2Gi }
      limits:   { cpu: 2000, memory: 1Gi,   ephemeral_storage: 4Gi }
    environment:
      PROJECT_ID: spectra-kube
      REGION: us-central1
      REPO: nexus
      APP_SECRETS_ENV:
        from_secret: uat_secrets_env
    commands:
      - |
        set -eux

        : "${PROJECT_ID:?missing}"; : "${REGION:?missing}"; : "${REPO:?missing}"
        REGISTRY="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}"
        printf '[deploy][uat] registry=%s\n' "$REGISTRY"

        # Secrets: prefer repo file for UAT, else Drone secret
        mkdir -p k8s/overlays/uat
        if [ -f backend/.env.uat ]; then
          tr -d '\r' < backend/.env.uat > k8s/overlays/uat/secrets.env
        elif [ -n "${APP_SECRETS_ENV:-}" ]; then
          printf '%s\n' "$APP_SECRETS_ENV" | tr -d '\r' > k8s/overlays/uat/secrets.env
        else
          echo "ERROR: no secrets provided (backend/.env.uat missing and APP_SECRETS_ENV empty)"; exit 1
        fi

        # Minimum validation
        for k in DB_USER DB_PASS; do
          grep -E "^[[:space:]]*$k=" k8s/overlays/uat/secrets.env >/uat/null || {
            echo "ERROR: required key '$k' missing in secrets.env"; exit 1; }
        done

        # Apply infra for UAT
        kubectl apply -k k8s/overlays/uat

        # Image digests (fallback to tags)
        bfile=/drone/src/backend-image.txt
        ffile=/drone/src/frontend-image.txt
        BACKEND_IMG=""; FRONTEND_IMG=""
        [ -s "$bfile" ] && BACKEND_IMG="$(tr -d '\r\n' < "$bfile")" || BACKEND_IMG="${REGISTRY}/nexus-backend:${DRONE_COMMIT_SHA}"
        [ -s "$ffile" ] && FRONTEND_IMG="$(tr -d '\r\n' < "$ffile")" || FRONTEND_IMG="${REGISTRY}/nexus-frontend:${DRONE_COMMIT_SHA}"

        printf '[deploy][uat] backend -> %s\n' "$BACKEND_IMG"
        printf '[deploy][uat] frontend -> %s\n' "$FRONTEND_IMG"

        kubectl -n uat set image deploy/backend  backend="$BACKEND_IMG"
        kubectl -n uat set image deploy/frontend frontend="$FRONTEND_IMG"

        kubectl -n uat get deploy backend  -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'
        kubectl -n uat get deploy frontend -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'

        set +e
        kubectl -n uat rollout status deploy/frontend --timeout=600s
        FE_RC=$?
        kubectl -n uat rollout status deploy/backend  --timeout=600s
        BK_RC=$?
        set -e

        if [ $BK_RC -ne 0 ] || [ $FE_RC -ne 0 ]; then
          echo "== DIAGNOSTICS (uat) =="
          kubectl -n uat get rs -o wide
          kubectl -n uat get pods -o wide
          kubectl -n uat get events --sort-by=.metadata.creationTimestamp | tail -n 100 || true
          kubectl -n uat describe deploy/backend || true
          kubectl -n uat describe pods -l app=backend || true
          exit 1
        fi

---
kind: pipeline
type: kubernetes
name: main
trigger: { branch: [main], event: [push] }
service_account_name: drone-pipeline

steps:
  - name: build-backend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=info
      - --context=dir://$DRONE_WORKSPACE/backend
      - --dockerfile=$DRONE_WORKSPACE/backend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/backend-image.txt
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 10Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 20Gi }

  - name: frontend-build
    image: node:20-bullseye
    environment:
      npm_config_fund: "false"
      npm_config_audit: "false"
      npm_config_progress: "false"
      npm_config_fetch_retries: "8"
      npm_config_fetch_retry_mintimeout: "30000"
      npm_config_fetch_retry_maxtimeout: "180000"
      npm_config_network_timeout: "600000"
      NODE_OPTIONS: "--max-old-space-size=1536"
    commands:
      - cd frontend
      - npm ci --no-audit --no-fund --loglevel=warn
      - npm run build
      - npm prune --omit=dev --omit=optional
      - npm dedupe --omit=dev || true
      - ls -lh build || true
      - du -sh build node_modules || true
    resources:
      requests: { cpu: 1000, memory: 2Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 4Gi, ephemeral_storage: 16Gi }

  - name: build-frontend
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ["/kaniko/executor"]
    command:
      - --verbosity=debug
      - --context=dir://$DRONE_WORKSPACE/frontend
      - --dockerfile=$DRONE_WORKSPACE/frontend/Dockerfile
      - --destination=us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend:${DRONE_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
      - --snapshot-mode=time
      - --single-snapshot
      - --compressed-caching=false
      - --use-new-run
      - --build-arg=COMMIT_SHA=${DRONE_COMMIT_SHA}
      - --image-name-with-digest-file=/drone/src/frontend-image.txt
    resources:
      requests: { cpu: 1000, memory: 1Gi, ephemeral_storage: 8Gi }
      limits:   { cpu: 2000, memory: 2Gi, ephemeral_storage: 16Gi }

  - name: deploy
    image: alpine/k8s:1.30.3
    pull: if-not-exists
    working_dir: /drone/src
    resources:
      requests: { cpu: 500, memory: 512Mi, ephemeral_storage: 2Gi }
      limits:   { cpu: 2000, memory: 1Gi,   ephemeral_storage: 4Gi }
    environment:
      PROJECT_ID: spectra-kube
      REGION: us-central1
      REPO: nexus
      APP_SECRETS_ENV:
        from_secret: main_secrets_env
    commands:
      - |
        set -eux

        : "${PROJECT_ID:?missing}"; : "${REGION:?missing}"; : "${REPO:?missing}"
        REGISTRY="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}"
        printf '[deploy][main] registry=%s\n' "$REGISTRY"

        # Secrets: prefer repo file for main, else Drone secret
        mkdir -p k8s/overlays/main
        if [ -f backend/.env.main ]; then
          tr -d '\r' < backend/.env.main > k8s/overlays/main/secrets.env
        elif [ -n "${APP_SECRETS_ENV:-}" ]; then
          printf '%s\n' "$APP_SECRETS_ENV" | tr -d '\r' > k8s/overlays/main/secrets.env
        else
          echo "ERROR: no secrets provided (backend/.env.main missing and APP_SECRETS_ENV empty)"; exit 1
        fi

        for k in DB_USER DB_PASS; do
          grep -E "^[[:space:]]*$k=" k8s/overlays/main/secrets.env >/main/null || {
            echo "ERROR: required key '$k' missing in secrets.env"; exit 1; }
        done

        # Apply infra for MAIN
        kubectl apply -k k8s/overlays/main

        # Image digests (fallback to tags)
        bfile=/drone/src/backend-image.txt
        ffile=/drone/src/frontend-image.txt
        BACKEND_IMG=""; FRONTEND_IMG=""
        [ -s "$bfile" ] && BACKEND_IMG="$(tr -d '\r\n' < "$bfile")" || BACKEND_IMG="${REGISTRY}/nexus-backend:${DRONE_COMMIT_SHA}"
        [ -s "$ffile" ] && FRONTEND_IMG="$(tr -d '\r\n' < "$ffile")" || FRONTEND_IMG="${REGISTRY}/nexus-frontend:${DRONE_COMMIT_SHA}"

        printf '[deploy][main] backend -> %s\n' "$BACKEND_IMG"
        printf '[deploy][main] frontend -> %s\n' "$FRONTEND_IMG"

        kubectl -n main set image deploy/backend  backend="$BACKEND_IMG"
        kubectl -n main set image deploy/frontend frontend="$FRONTEND_IMG"

        kubectl -n main get deploy backend  -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'
        kubectl -n main get deploy frontend -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'

        set +e
        kubectl -n main rollout status deploy/frontend --timeout=600s
        FE_RC=$?
        kubectl -n main rollout status deploy/backend  --timeout=600s
        BK_RC=$?
        set -e

        if [ $BK_RC -ne 0 ] || [ $FE_RC -ne 0 ]; then
          echo "== DIAGNOSTICS (main) =="
          kubectl -n main get rs -o wide
          kubectl -n main get pods -o wide
          kubectl -n main get events --sort-by=.metadata.creationTimestamp | tail -n 100 || true
          kubectl -n main describe deploy/backend || true
          kubectl -n main describe pods -l app=backend || true
          exit 1
        fi