-- db/init/01-create-users.sql
-- Run in FREEPDB1 and be idempotent.

-- Ensure we are in the PDB:
ALTER SESSION SET CONTAINER=FREEPDB1;

-- Do NOT set "_ORACLE_SCRIPT" here; it's for CDB/common users.

-- NEXUS_DEV
DECLARE v_count NUMBER; BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username='NEXUS_DEV';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE USER NEXUS_DEV IDENTIFIED BY dev_pass DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS]';
    EXECUTE IMMEDIATE q'[GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO NEXUS_DEV]';
  ELSE
    EXECUTE IMMEDIATE q'[ALTER USER NEXUS_DEV IDENTIFIED BY dev_pass ACCOUNT UNLOCK]';
    EXECUTE IMMEDIATE q'[ALTER USER NEXUS_DEV QUOTA UNLIMITED ON USERS]';
  END IF;
END;
/

-- NEXUS_UAT
DECLARE v_count NUMBER; BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username='NEXUS_UAT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE USER NEXUS_UAT IDENTIFIED BY uat_pass DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS]';
    EXECUTE IMMEDIATE q'[GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO NEXUS_UAT]';
  ELSE
    EXECUTE IMMEDIATE q'[ALTER USER NEXUS_UAT IDENTIFIED BY uat_pass ACCOUNT UNLOCK]';
    EXECUTE IMMEDIATE q'[ALTER USER NEXUS_UAT QUOTA UNLIMITED ON USERS]';
  END IF;
END;
/

-- NEXUS_PROD
DECLARE v_count NUMBER; BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username='NEXUS_PROD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE USER NEXUS_PROD IDENTIFIED BY prod_pass DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS]';
    EXECUTE IMMEDIATE q'[GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO NEXUS_PROD]';
  ELSE
    EXECUTE IMMEDIATE q'[ALTER USER NEXUS_PROD IDENTIFIED BY prod_pass ACCOUNT UNLOCK]';
    EXECUTE IMMEDIATE q'[ALTER USER NEXUS_PROD QUOTA UNLIMITED ON USERS]';
  END IF;
END;
/
