apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: main
resources:
  - ../../base

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

images:
  - name: us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend
    newTag: main
  - name: us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend
    newTag: main

configMapGenerator:
  - name: nexus-backend-config
    literals:
      - SPRING_PROFILES_ACTIVE=main
      - DB_URL=jdbc:oracle:thin:@//oracle.db.svc.cluster.local:1521/FREEPDB1
  - name: nexus-frontend-config    
    behavior: merge
    literals:
      - PUBLIC_BACKEND_URL=http://backend:8080/nexus

secretGenerator:
  - name: nexus-backend-secrets
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - backend-env.patch.yml
  - backend-waitdb.patch.yml
  - backend-probes.jsonpatch.yml
  - imagepull-always-backend.patch.yml
  - imagepull-always-frontend.patch.yml

patches:
  # JSON6902 patch to REPLACE probes with tcp sockets
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: backend-probes.jsonpatch.yml