apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
  namespace: db
spec:
  template:
    spec:
      securityContext:
        fsGroup: 54321
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: fix-oradata-perms
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              chown -R 54321:54321 /opt/oracle/oradata &&
              chmod -R g+rwX /opt/oracle/oradata
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /opt/oracle/oradata
      containers:
        - name: oracle
          securityContext:
            runAsUser: 54321
            runAsGroup: 54321
            allowPrivilegeEscalation: false