apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: drone-server
  namespace: ci
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
      app.kubernetes.io/component: server
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      authorization:
        type: Bearer
        credentials:
          secret:
            name: drone-metrics-token
            key: token