apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gmp-collector-read-secrets
  namespace: ci
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gmp-collector-read-secrets
  namespace: ci
subjects:
- kind: ServiceAccount
  name: collector
  namespace: gke-gmp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gmp-collector-read-secrets