apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-bc
  namespace: dev
spec:
  healthCheck:
    requestPath: /
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3