apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
resources:
  - ../../base

images:
  - name: us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend
    newTag: dev
  - name: us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend
    newTag: dev

configMapGenerator:
  - name: nexus-backend-config
    literals:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=jdbc:oracle:thin:@//oracle.db.svc.cluster.local:1521/FREEPDB1
  - name: nexus-frontend-config
    literals:
      - VITE_API_URL=http://backend:8080

secretGenerator:
  - name: nexus-backend-secrets
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true

# Keep your existing strategic-merge patches (env + wait-db)
patchesStrategicMerge:
  - backend-env.patch.yml
  - backend-waitdb.patch.yml

# Use JSON6902 patch to fully replace probes with tcpSocket versions
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: backend-probes.jsonpatch.yml