apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  template:
    spec:
      containers:
      - name: locust
        env:
        - name: LOCUST_HOST
          value: "http://backend.dev.svc.cluster.local:8080/nexus"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  template:
    spec:
      containers:
      - name: locust
        env:
        - name: LOCUST_HOST
          value: "http://backend.dev.svc.cluster.local:8080/nexus"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-run
spec:
  template:
    spec:
      containers:
      - name: jmeter
        env:
        - name: TARGET_BASE_URL
          value: "http://backend.dev.svc.cluster.local:8080/nexus"