apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: PUBLIC_BACKEND_URL
          value: "/nexus"
        - name: PRIVATE_BACKEND_URL
          value: "http://backend.dev.svc.cluster.local:8080/nexus"