apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat
resources:
  - ../../base

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

images:
  - name: us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-backend
    newTag: uat
  - name: us-central1-docker.pkg.dev/spectra-kube/nexus/nexus-frontend
    newTag: uat

configMapGenerator:
  - name: nexus-backend-config
    literals:
      - SPRING_PROFILES_ACTIVE=uat
      - DB_URL=jdbc:oracle:thin:@//oracle.db.svc.cluster.local:1521/FREEPDB1
  - name: nexus-frontend-config    
    behavior: merge
    literals:
      - PUBLIC_BACKEND_URL=http://backend:8080/nexus

secretGenerator:
  - name: nexus-backend-secrets
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target: { group: apps, version: v1, kind: Deployment, name: backend }
    path: backend-env.patch.yml
  - target: { group: apps, version: v1, kind: Deployment, name: backend }
    path: backend-waitdb.patch.yml
  - target: { group: apps, version: v1, kind: Deployment, name: backend }
    path: backend-probes.jsonpatch.yml