apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: nexus-frontend
  namespace: uat
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s