apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podmonitoring-admin-binding
  namespace: uat
subjects:
- kind: ServiceAccount
  name: drone-pipeline
  namespace: ci  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podmonitoring-admin