name: CI - Frontend SonarQube

on:
  pull_request:
    branches: [dev, uat, main]
  workflow_dispatch:

jobs:
  sonar-frontend:
    name: Sonar Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
    outputs:
      analyzed: ${{ steps.changes.outputs.frontend }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - '.github/workflows/ci-sonar-frontend.yml'

      - name: Setup Node
        if: steps.changes.outputs.frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        if: steps.changes.outputs.frontend == 'true'
        run: npm ci

      - name: Run smoke tests + coverage
        if: steps.changes.outputs.frontend == 'true'
        run: npm run test:smoke:cov

      # --- Sonar scan (self-hosted SonarQube) ---
      - name: SonarQube Scan
        if: steps.changes.outputs.frontend == 'true'
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: frontend

      # Wait for the Quality Gate (blocks merge if fails)
      - name: SonarQube Quality Gate
        if: steps.changes.outputs.frontend == 'true'
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: No frontend changes — skip analysis
        if: steps.changes.outputs.frontend != 'true'
        run: echo "No frontend changes detected; skipping Sonar."
